services:
  database:
    image: shamebot/database
    build:
      context: database
      dockerfile: ./docker/Dockerfile
    ports:
      - 8001:5432
  cron:
    image: shamebot/cron
    build:
      context: .
      dockerfile: ./cron/docker/Dockerfile
    ports:
      - 8080:8080      
  api:
    image: shamebot/api
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    ports:
      - 8000:8000
